# Curtesy of blog post: https://petercoding.com/flutter/2021/07/18/using-github-actions-with-flutter/
name: Flutter Analysis & Test

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "master" ]
  
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "21"
      FLUTTER_VERSION: "3.22.1"
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '$JAVA_VERSION'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: $FLUTTER_VERSION
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze project
        run: flutter analyze
      - name: Test project
        run: flutter test
